### ISSUE TITLE
CKAN API response is truncated and we cannot access the count value

### ISSUE THREAD

**Issue by thhomas** [itisem/ckan-ts#1]
Thank you for your work, I am trying to build a web application to connect to CKAN with your library.
For my application, I need to get the count result for each search in order to build a pagination component.
Unfortunately, in all the available methods (all based on the `action` method) [the output is only limited to the `result` part of the CKAN API response](https://github.com/itisem/ckan-ts/blob/main/src/ckan.ts#L217) and some field such as `count` are not made available.

**Comment by itisem** [comment]
merged commits and published new version
